name: .NET Core Web API CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
#      - name: Build the project
#        run: dotnet build --configuration Release --no-restore

  # GitHub Advanced Security scan job
  security_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Run CodeQL analysis for GitHub Advanced Security
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: "csharp"

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2
